### PR TITLE
Updated URLs to point to relevant v3006.8.0 version

### PR DESCRIPTION
**Pull request by LeaDevelop**
Corrected doc and release notes URLs to point to 3006/.8 documentation.
Replaced obsolete URL and one that's expected to use based on official Saltstack's documentation.

### CODE REVIEW

**Comment by barkingfoodog** [comment]
Hi, thank you for the update! Would you please move the `tools/` directory one level higher and eliminate the `saltminion/` directory? This will allow the relative path in `saltminion.nuspec` to locate the files under `tools/`.

**Comment by LeaDevelop** [comment]
> Hi, thank you for the update! Would you please move the `tools/` directory one level higher and eliminate the `saltminion/` directory? This will allow the relative path in `saltminion.nuspec` to locate the files under `tools/`.

Sure thing, will take care of it later today 👍🏻

**Comment by LeaDevelop** [comment]
Didn't get to it yesterday, I'll be on it in ~2h and sort all other PRs as well 👍🏻 thank you for the review!

**Comment by LeaDevelop** [comment]
@barkingfoodog PR was aligned with master branch and suggested improvements done, ready for review

**Comment by barkingfoodog** [comment]
@LeaDevelop thanks! I'm going to work through these PRs starting with the newest (this one), pushing each package to chocolatey and waiting for it to be approved before proceeding to the next. That will help me keep track of what versions are where.

Chocolatey review can take a few hours, so this will take a couple days to sort.

**Comment by LeaDevelop** [comment]
Thank you!

**Pull request merged**
